sudo: false
language: ruby
rvm: 2.3.4
cache:
  bundler: true
addons:
  firefox: "latest"
services:
  - postgresql
env:
  - DB_ENV_POSTGRESQL_USER_TEST=postgres
install:
  - bundle config gems.contribsys.com $SIDEKIQ_CREDS
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - bundle exec rake db:create db:setup RAILS_ENV=test
script:
  - bundle exec rake